// Generated by CoffeeScript 1.10.0
var Currency, StorySegment, TeamMember, crystals, first_launch, first_run, gold, segment1, xp;

Currency = (function() {
  function Currency(name, amount1) {
    this.name = name;
    this.amount = amount1;
    this.spend = function(amount) {
      return this.amount -= amount;
    };
    this.gain = function() {
      return this.amount += amount;
    };
  }

  return Currency;

})();

gold = new Currency("Gold", 5000);

xp = new Currency("Experience", 0);

crystals = new Currency("Crystals", 150);

TeamMember = (function() {
  function TeamMember(name, main_stat) {
    this.name = name;
    this.str = 1;
    this.fort = 1;
    this.dex = 1;
    this.speed = 1;
    this.energy = 20;
    this.skill_points = 0;
    this.total_xp_gained = 0;
    this.hp = function() {
      return this.fort * 10;
    };
    this.crit_dmg = function() {
      return 1 + ((this.dex + this.str) / 100);
    };
    this.base_dmg = function() {
      return this.str * 1.5;
    };
    this.armor = function() {
      return this.fort * 0.5;
    };
    this.crit_chance = function() {
      return this.dex / 100;
    };
    this.dodge = function() {
      return 1 + ((this.speed + this.dex) / 100);
    };
    this.lvl = function() {
      return 1;
    };
  }

  return TeamMember;

})();

StorySegment = (function() {
  function StorySegment(num, name, images) {
    this.num = num;
    this.name = name;
    this.images = images;
    this.show = function() {
      var html, x;
      x = 0;
      html = "<div id='story-segment-1' class='container-fluid modal fade'>" + "<div class='modal-dialog modal-lg' role='document'>" + "<div class='modal-content'>" + "<div class='modal-header'>" + "<button id='story-close' type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>" + "<h4 class='modal-title' id='myModalLabel'>" + this.num + " - " + this.name + "</h4>" + "</div>" + "<div class='modal-body'>" + "<img class='story-image' src=" + this.images[x] + " class='row' />" + "</div>" + "<div class='modal-footer'>" + "</div>" + "</div>" + "</div>" + "</div>";
      $('body').append(html);
      $('#story-segment-1').modal({
        "show": "true",
        backdrop: "static"
      });
      return $('.story-image').click((function(_this) {
        return function() {
          x += 1;
          return $('.story-image').attr('src', _this.images[x]);
        };
      })(this));
    };
  }

  return StorySegment;

})();

segment1 = new StorySegment(1, "Let's get out of here...", ["img/tube1.jpg", "img/tube2.jpg", "img/tube3.jpg", "img/tube4.jpg", "img/tube5.jpg", "img/tube6.jpg", "img/tube7.jpg", "img/tube8.jpg", "img/tube9.jpg"]);

first_launch = function() {
  return true;
};

first_run = function() {
  if (first_launch) {
    return segment1.show();
  }
};

$(document).ready(function() {
  return first_run();
});


/*
  window.setInterval( ->

  , 1000)

StorySegment
TeamMember
Mission
Achievement
Currency
960x430 is standard size for main_image
960x430 = 900
 */
